# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cleanarchitectureappwebapi:
    image: cleanarchitectureappwebapi
    build:
      context: .
      dockerfile: CleanArchitectureApp.WebApi/Dockerfile
  
  portainer:
    image: portainer/portainer-ce 
    
  mssqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  
volumes:
  portainer_data: