# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  cleanarchitectureappwebapi:
    image: cleanarchitectureappwebapi
    build:
      context: .
      dockerfile: CleanArchitectureApp.WebApi/Dockerfile
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
